### ISSUE TITLE
Error in installing cybercaptor-server 4.4.3

### ISSUE THREAD

**Issue by zhangshuqin** [fiware-cybercaptor/cybercaptor-server#9]
A problem has been encountered while installing cybercaptor-server 4.4.3 following the guide document: "`pwd`/configuration-files" and "`pwd`/src/main/python/" do not exist in the project package.

**Comment by fxaguessy** [comment]
The documentation was not exactly updated. I corrected the README file in b6b1f1046d6b.

However, the `"``pwd``/configuration-files"` was already existing in the project package.

It should be clearer now.

For information, it may be easier to test cybercaptor, using the docker container.
